/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemarketerRouteImport } from './routes/telemarketer'
import { Route as TeamChatRouteImport } from './routes/team-chat'
import { Route as TeamAgentsRouteImport } from './routes/team-agents'
import { Route as SharkTankRouteImport } from './routes/shark-tank'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyLeadsRouteImport } from './routes/my-leads'
import { Route as LiveleadsRouteImport } from './routes/liveleads'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as ChipPreviewRouteImport } from './routes/chip-preview'
import { Route as CallQueueRouteImport } from './routes/call-queue'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeamChatAdminRouteImport } from './routes/team-chat.admin'
import { Route as PrototypeVendorImportRouteImport } from './routes/prototype.vendor-import'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DevAlertPreviewRouteImport } from './routes/dev.alert-preview'
import { Route as AiSettingsRouteImport } from './routes/ai.settings'
import { Route as AdminScoringRouteImport } from './routes/admin.scoring'
import { Route as AdminPostingRouteImport } from './routes/admin.posting'
import { Route as AdminDisposRouteImport } from './routes/admin.dispos'
import { Route as AdminDebugOncallRouteImport } from './routes/admin.debug-oncall'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSaleNotifyRouteImport } from './routes/api/public/sale-notify'
import { Route as ApiPublicNotifyAccessRequestRouteImport } from './routes/api/public/notify-access-request'
import { Route as ApiPublicAddressSuggestRouteImport } from './routes/api/public/address-suggest'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as AgentsAgentIdActivityRouteImport } from './routes/agents.$agentId.activity'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksZillowBackfillRouteImport } from './routes/api/public/hooks/zillow-backfill'
import { Route as ApiPublicHooksEmailHealthRouteImport } from './routes/api/public/hooks/email-health'
import { Route as ApiPublicLeadsPostTokenRouteImport } from './routes/api/public/leads/post.$token'

const TelemarketerRoute = TelemarketerRouteImport.update({
  id: '/telemarketer',
  path: '/telemarketer',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamChatRoute = TeamChatRouteImport.update({
  id: '/team-chat',
  path: '/team-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAgentsRoute = TeamAgentsRouteImport.update({
  id: '/team-agents',
  path: '/team-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const SharkTankRoute = SharkTankRouteImport.update({
  id: '/shark-tank',
  path: '/shark-tank',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeadsRoute = MyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveleadsRoute = LiveleadsRouteImport.update({
  id: '/liveleads',
  path: '/liveleads',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChipPreviewRoute = ChipPreviewRouteImport.update({
  id: '/chip-preview',
  path: '/chip-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CallQueueRoute = CallQueueRouteImport.update({
  id: '/call-queue',
  path: '/call-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamChatAdminRoute = TeamChatAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TeamChatRoute,
} as any)
const PrototypeVendorImportRoute = PrototypeVendorImportRouteImport.update({
  id: '/prototype/vendor-import',
  path: '/prototype/vendor-import',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAlertPreviewRoute = DevAlertPreviewRouteImport.update({
  id: '/dev/alert-preview',
  path: '/dev/alert-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AiRoute,
} as any)
const AdminScoringRoute = AdminScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostingRoute = AdminPostingRouteImport.update({
  id: '/posting',
  path: '/posting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisposRoute = AdminDisposRouteImport.update({
  id: '/dispos',
  path: '/dispos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugOncallRoute = AdminDebugOncallRouteImport.update({
  id: '/debug-oncall',
  path: '/debug-oncall',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaleNotifyRoute = ApiPublicSaleNotifyRouteImport.update({
  id: '/api/public/sale-notify',
  path: '/api/public/sale-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyAccessRequestRoute =
  ApiPublicNotifyAccessRequestRouteImport.update({
    id: '/api/public/notify-access-request',
    path: '/api/public/notify-access-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAddressSuggestRoute = ApiPublicAddressSuggestRouteImport.update({
  id: '/api/public/address-suggest',
  path: '/api/public/address-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdActivityRoute = AgentsAgentIdActivityRouteImport.update({
  id: '/agents/$agentId/activity',
  path: '/agents/$agentId/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksZillowBackfillRoute =
  ApiPublicHooksZillowBackfillRouteImport.update({
    id: '/api/public/hooks/zillow-backfill',
    path: '/api/public/hooks/zillow-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailHealthRoute =
  ApiPublicHooksEmailHealthRouteImport.update({
    id: '/api/public/hooks/email-health',
    path: '/api/public/hooks/email-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsPostTokenRoute = ApiPublicLeadsPostTokenRouteImport.update({
  id: '/api/public/leads/post/$token',
  path: '/api/public/leads/post/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/call-queue': typeof CallQueueRoute
  '/chip-preview': typeof ChipPreviewRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/insights': typeof InsightsRoute
  '/liveleads': typeof LiveleadsRoute
  '/my-leads': typeof MyLeadsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shark-tank': typeof SharkTankRoute
  '/team-agents': typeof TeamAgentsRoute
  '/team-chat': typeof TeamChatRouteWithChildren
  '/telemarketer': typeof TelemarketerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/debug-oncall': typeof AdminDebugOncallRoute
  '/admin/dispos': typeof AdminDisposRoute
  '/admin/posting': typeof AdminPostingRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/ai/settings': typeof AiSettingsRoute
  '/dev/alert-preview': typeof DevAlertPreviewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/prototype/vendor-import': typeof PrototypeVendorImportRoute
  '/team-chat/admin': typeof TeamChatAdminRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/address-suggest': typeof ApiPublicAddressSuggestRoute
  '/api/public/notify-access-request': typeof ApiPublicNotifyAccessRequestRoute
  '/api/public/sale-notify': typeof ApiPublicSaleNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/email-health': typeof ApiPublicHooksEmailHealthRoute
  '/api/public/hooks/zillow-backfill': typeof ApiPublicHooksZillowBackfillRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/leads/post/$token': typeof ApiPublicLeadsPostTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/call-queue': typeof CallQueueRoute
  '/chip-preview': typeof ChipPreviewRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/insights': typeof InsightsRoute
  '/liveleads': typeof LiveleadsRoute
  '/my-leads': typeof MyLeadsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shark-tank': typeof SharkTankRoute
  '/team-agents': typeof TeamAgentsRoute
  '/team-chat': typeof TeamChatRouteWithChildren
  '/telemarketer': typeof TelemarketerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/debug-oncall': typeof AdminDebugOncallRoute
  '/admin/dispos': typeof AdminDisposRoute
  '/admin/posting': typeof AdminPostingRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/ai/settings': typeof AiSettingsRoute
  '/dev/alert-preview': typeof DevAlertPreviewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/prototype/vendor-import': typeof PrototypeVendorImportRoute
  '/team-chat/admin': typeof TeamChatAdminRoute
  '/admin': typeof AdminIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/address-suggest': typeof ApiPublicAddressSuggestRoute
  '/api/public/notify-access-request': typeof ApiPublicNotifyAccessRequestRoute
  '/api/public/sale-notify': typeof ApiPublicSaleNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/email-health': typeof ApiPublicHooksEmailHealthRoute
  '/api/public/hooks/zillow-backfill': typeof ApiPublicHooksZillowBackfillRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/leads/post/$token': typeof ApiPublicLeadsPostTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/call-queue': typeof CallQueueRoute
  '/chip-preview': typeof ChipPreviewRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/insights': typeof InsightsRoute
  '/liveleads': typeof LiveleadsRoute
  '/my-leads': typeof MyLeadsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shark-tank': typeof SharkTankRoute
  '/team-agents': typeof TeamAgentsRoute
  '/team-chat': typeof TeamChatRouteWithChildren
  '/telemarketer': typeof TelemarketerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/debug-oncall': typeof AdminDebugOncallRoute
  '/admin/dispos': typeof AdminDisposRoute
  '/admin/posting': typeof AdminPostingRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/ai/settings': typeof AiSettingsRoute
  '/dev/alert-preview': typeof DevAlertPreviewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/prototype/vendor-import': typeof PrototypeVendorImportRoute
  '/team-chat/admin': typeof TeamChatAdminRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/address-suggest': typeof ApiPublicAddressSuggestRoute
  '/api/public/notify-access-request': typeof ApiPublicNotifyAccessRequestRoute
  '/api/public/sale-notify': typeof ApiPublicSaleNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/email-health': typeof ApiPublicHooksEmailHealthRoute
  '/api/public/hooks/zillow-backfill': typeof ApiPublicHooksZillowBackfillRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/leads/post/$token': typeof ApiPublicLeadsPostTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/call-queue'
    | '/chip-preview'
    | '/commissions'
    | '/dashboard'
    | '/follow-ups'
    | '/insights'
    | '/liveleads'
    | '/my-leads'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/shark-tank'
    | '/team-agents'
    | '/team-chat'
    | '/telemarketer'
    | '/admin/activity'
    | '/admin/debug-oncall'
    | '/admin/dispos'
    | '/admin/posting'
    | '/admin/scoring'
    | '/ai/settings'
    | '/dev/alert-preview'
    | '/email/unsubscribe'
    | '/leads/$leadId'
    | '/leads/new'
    | '/prototype/vendor-import'
    | '/team-chat/admin'
    | '/admin/'
    | '/agents/$agentId/activity'
    | '/api/ai/chat'
    | '/api/public/address-suggest'
    | '/api/public/notify-access-request'
    | '/api/public/sale-notify'
    | '/lovable/email/suppression'
    | '/api/public/hooks/email-health'
    | '/api/public/hooks/zillow-backfill'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/leads/post/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/call-queue'
    | '/chip-preview'
    | '/commissions'
    | '/dashboard'
    | '/follow-ups'
    | '/insights'
    | '/liveleads'
    | '/my-leads'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/shark-tank'
    | '/team-agents'
    | '/team-chat'
    | '/telemarketer'
    | '/admin/activity'
    | '/admin/debug-oncall'
    | '/admin/dispos'
    | '/admin/posting'
    | '/admin/scoring'
    | '/ai/settings'
    | '/dev/alert-preview'
    | '/email/unsubscribe'
    | '/leads/$leadId'
    | '/leads/new'
    | '/prototype/vendor-import'
    | '/team-chat/admin'
    | '/admin'
    | '/agents/$agentId/activity'
    | '/api/ai/chat'
    | '/api/public/address-suggest'
    | '/api/public/notify-access-request'
    | '/api/public/sale-notify'
    | '/lovable/email/suppression'
    | '/api/public/hooks/email-health'
    | '/api/public/hooks/zillow-backfill'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/leads/post/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/call-queue'
    | '/chip-preview'
    | '/commissions'
    | '/dashboard'
    | '/follow-ups'
    | '/insights'
    | '/liveleads'
    | '/my-leads'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/shark-tank'
    | '/team-agents'
    | '/team-chat'
    | '/telemarketer'
    | '/admin/activity'
    | '/admin/debug-oncall'
    | '/admin/dispos'
    | '/admin/posting'
    | '/admin/scoring'
    | '/ai/settings'
    | '/dev/alert-preview'
    | '/email/unsubscribe'
    | '/leads/$leadId'
    | '/leads/new'
    | '/prototype/vendor-import'
    | '/team-chat/admin'
    | '/admin/'
    | '/agents/$agentId/activity'
    | '/api/ai/chat'
    | '/api/public/address-suggest'
    | '/api/public/notify-access-request'
    | '/api/public/sale-notify'
    | '/lovable/email/suppression'
    | '/api/public/hooks/email-health'
    | '/api/public/hooks/zillow-backfill'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/leads/post/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  CallQueueRoute: typeof CallQueueRoute
  ChipPreviewRoute: typeof ChipPreviewRoute
  CommissionsRoute: typeof CommissionsRoute
  DashboardRoute: typeof DashboardRoute
  FollowUpsRoute: typeof FollowUpsRoute
  InsightsRoute: typeof InsightsRoute
  LiveleadsRoute: typeof LiveleadsRoute
  MyLeadsRoute: typeof MyLeadsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SharkTankRoute: typeof SharkTankRoute
  TeamAgentsRoute: typeof TeamAgentsRoute
  TeamChatRoute: typeof TeamChatRouteWithChildren
  TelemarketerRoute: typeof TelemarketerRoute
  DevAlertPreviewRoute: typeof DevAlertPreviewRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  PrototypeVendorImportRoute: typeof PrototypeVendorImportRoute
  AgentsAgentIdActivityRoute: typeof AgentsAgentIdActivityRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiPublicAddressSuggestRoute: typeof ApiPublicAddressSuggestRoute
  ApiPublicNotifyAccessRequestRoute: typeof ApiPublicNotifyAccessRequestRoute
  ApiPublicSaleNotifyRoute: typeof ApiPublicSaleNotifyRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksEmailHealthRoute: typeof ApiPublicHooksEmailHealthRoute
  ApiPublicHooksZillowBackfillRoute: typeof ApiPublicHooksZillowBackfillRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicLeadsPostTokenRoute: typeof ApiPublicLeadsPostTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemarketer': {
      id: '/telemarketer'
      path: '/telemarketer'
      fullPath: '/telemarketer'
      preLoaderRoute: typeof TelemarketerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-chat': {
      id: '/team-chat'
      path: '/team-chat'
      fullPath: '/team-chat'
      preLoaderRoute: typeof TeamChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-agents': {
      id: '/team-agents'
      path: '/team-agents'
      fullPath: '/team-agents'
      preLoaderRoute: typeof TeamAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shark-tank': {
      id: '/shark-tank'
      path: '/shark-tank'
      fullPath: '/shark-tank'
      preLoaderRoute: typeof SharkTankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leads': {
      id: '/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof MyLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveleads': {
      id: '/liveleads'
      path: '/liveleads'
      fullPath: '/liveleads'
      preLoaderRoute: typeof LiveleadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chip-preview': {
      id: '/chip-preview'
      path: '/chip-preview'
      fullPath: '/chip-preview'
      preLoaderRoute: typeof ChipPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-queue': {
      id: '/call-queue'
      path: '/call-queue'
      fullPath: '/call-queue'
      preLoaderRoute: typeof CallQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/team-chat/admin': {
      id: '/team-chat/admin'
      path: '/admin'
      fullPath: '/team-chat/admin'
      preLoaderRoute: typeof TeamChatAdminRouteImport
      parentRoute: typeof TeamChatRoute
    }
    '/prototype/vendor-import': {
      id: '/prototype/vendor-import'
      path: '/prototype/vendor-import'
      fullPath: '/prototype/vendor-import'
      preLoaderRoute: typeof PrototypeVendorImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/alert-preview': {
      id: '/dev/alert-preview'
      path: '/dev/alert-preview'
      fullPath: '/dev/alert-preview'
      preLoaderRoute: typeof DevAlertPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/settings': {
      id: '/ai/settings'
      path: '/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof AiRoute
    }
    '/admin/scoring': {
      id: '/admin/scoring'
      path: '/scoring'
      fullPath: '/admin/scoring'
      preLoaderRoute: typeof AdminScoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posting': {
      id: '/admin/posting'
      path: '/posting'
      fullPath: '/admin/posting'
      preLoaderRoute: typeof AdminPostingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispos': {
      id: '/admin/dispos'
      path: '/dispos'
      fullPath: '/admin/dispos'
      preLoaderRoute: typeof AdminDisposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/debug-oncall': {
      id: '/admin/debug-oncall'
      path: '/debug-oncall'
      fullPath: '/admin/debug-oncall'
      preLoaderRoute: typeof AdminDebugOncallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sale-notify': {
      id: '/api/public/sale-notify'
      path: '/api/public/sale-notify'
      fullPath: '/api/public/sale-notify'
      preLoaderRoute: typeof ApiPublicSaleNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-access-request': {
      id: '/api/public/notify-access-request'
      path: '/api/public/notify-access-request'
      fullPath: '/api/public/notify-access-request'
      preLoaderRoute: typeof ApiPublicNotifyAccessRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/address-suggest': {
      id: '/api/public/address-suggest'
      path: '/api/public/address-suggest'
      fullPath: '/api/public/address-suggest'
      preLoaderRoute: typeof ApiPublicAddressSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/activity': {
      id: '/agents/$agentId/activity'
      path: '/agents/$agentId/activity'
      fullPath: '/agents/$agentId/activity'
      preLoaderRoute: typeof AgentsAgentIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/zillow-backfill': {
      id: '/api/public/hooks/zillow-backfill'
      path: '/api/public/hooks/zillow-backfill'
      fullPath: '/api/public/hooks/zillow-backfill'
      preLoaderRoute: typeof ApiPublicHooksZillowBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-health': {
      id: '/api/public/hooks/email-health'
      path: '/api/public/hooks/email-health'
      fullPath: '/api/public/hooks/email-health'
      preLoaderRoute: typeof ApiPublicHooksEmailHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/post/$token': {
      id: '/api/public/leads/post/$token'
      path: '/api/public/leads/post/$token'
      fullPath: '/api/public/leads/post/$token'
      preLoaderRoute: typeof ApiPublicLeadsPostTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminDebugOncallRoute: typeof AdminDebugOncallRoute
  AdminDisposRoute: typeof AdminDisposRoute
  AdminPostingRoute: typeof AdminPostingRoute
  AdminScoringRoute: typeof AdminScoringRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminDebugOncallRoute: AdminDebugOncallRoute,
  AdminDisposRoute: AdminDisposRoute,
  AdminPostingRoute: AdminPostingRoute,
  AdminScoringRoute: AdminScoringRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiRouteChildren {
  AiSettingsRoute: typeof AiSettingsRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiSettingsRoute: AiSettingsRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface TeamChatRouteChildren {
  TeamChatAdminRoute: typeof TeamChatAdminRoute
}

const TeamChatRouteChildren: TeamChatRouteChildren = {
  TeamChatAdminRoute: TeamChatAdminRoute,
}

const TeamChatRouteWithChildren = TeamChatRoute._addFileChildren(
  TeamChatRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  CallQueueRoute: CallQueueRoute,
  ChipPreviewRoute: ChipPreviewRoute,
  CommissionsRoute: CommissionsRoute,
  DashboardRoute: DashboardRoute,
  FollowUpsRoute: FollowUpsRoute,
  InsightsRoute: InsightsRoute,
  LiveleadsRoute: LiveleadsRoute,
  MyLeadsRoute: MyLeadsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SharkTankRoute: SharkTankRoute,
  TeamAgentsRoute: TeamAgentsRoute,
  TeamChatRoute: TeamChatRouteWithChildren,
  TelemarketerRoute: TelemarketerRoute,
  DevAlertPreviewRoute: DevAlertPreviewRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  PrototypeVendorImportRoute: PrototypeVendorImportRoute,
  AgentsAgentIdActivityRoute: AgentsAgentIdActivityRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiPublicAddressSuggestRoute: ApiPublicAddressSuggestRoute,
  ApiPublicNotifyAccessRequestRoute: ApiPublicNotifyAccessRequestRoute,
  ApiPublicSaleNotifyRoute: ApiPublicSaleNotifyRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksEmailHealthRoute: ApiPublicHooksEmailHealthRoute,
  ApiPublicHooksZillowBackfillRoute: ApiPublicHooksZillowBackfillRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicLeadsPostTokenRoute: ApiPublicLeadsPostTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
